class CreateCandidates < ActiveRecord::Migration
  def change
    create_table :candidates do |t|
      t.date :date_of_apply
      t.string :first_name
      t.string :last_name
      t.string :city_of_birth
      t.date :date_of_birth
      t.string :country_of_birth
      t.string :current_location
      t.string :preferred_work_location
      t.string :preferred_contact_phone
      t.string :email
      t.string :language1
      t.string :language1_level
      t.string :language2
      t.string :language2_level
      t.string :language3
      t.string :language3_level
      t.string :language4
      t.string :language4_level
      t.string :language5
      t.string :language5_level
      t.string :language6
      t.string :language6_level
      t.string :language7
      t.string :language7_level
      t.string :language8
      t.string :language8_level
      t.string :language9
      t.string :language9_level
      t.string :language10
      t.string :language10_level
      t.date :education1_start_date
      t.date :education1_end_date
      t.string :univercity1
      t.string :major1
      t.string :education1_level
      t.string :note1
      t.date :education2_start_date
      t.date :education2_end_date
      t.string :univercity2
      t.string :major2
      t.string :education2_level
      t.string :note2
      t.date :education3_start_date
      t.date :education3_end_date
      t.string :univercity3
      t.string :major3
      t.string :education3_level
      t.string :note3
      t.date :education4_start_date
      t.date :education4_end_date
      t.string :univercity4
      t.string :major4
      t.string :education4_level
      t.string :note4
      t.date :education5_start_date
      t.date :education5_end_date
      t.string :univercity5
      t.string :major5
      t.string :education5_level
      t.string :note5
      t.date :work1_start_date
      t.date :work1_end_date
      t.string :company1
      t.string :title1
      t.string :work1_desc
      t.date :work2_start_date
      t.date :work2_end_date
      t.string :company2
      t.string :title2
      t.string :work2_desc
      t.date :work3_start_date
      t.date :work3_end_date
      t.string :company3
      t.string :title3
      t.string :work3_desc
      t.date :work4_start_date
      t.date :work4_end_date
      t.string :company4
      t.string :title4
      t.string :work4_desc
      t.date :work5_start_date
      t.date :work5_end_date
      t.string :company5
      t.string :title5
      t.string :work5_desc
      t.string :ex_merkler
      t.string :current_job_title
      t.integer :current_salary
      t.integer :expect_salary
      t.date :onboard_date
      t.string :self_assessment
      t.string :channel
      t.string :channel_detail
      t.string :referred_by
      t.string :req_position_title
      t.integer :candidate_id
      t.string :field1
      t.string :field2
      t.string :field3
      t.string :field4
      t.string :field5
      t.string :field6
      t.string :field7
      t.string :field8
      t.string :field9
      t.string :field10

      t.timestamps
    end
  end
end
